# Generated by Django 4.1.3 on 2023-01-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='credits',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
